[package]
name = "rcf"
version = "0.1.0"
edition = "2021"
authors = ["Raudel Alejandro Gómez Molina <raudel.gmolina@gmail.com>"]
readme = "README.md"
license-file = "LICENCE"
repository = "https://github.com/raudel25/rcf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
scraper = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
